### ISSUE TITLE
Get technical details from the XTF

### ISSUE THREAD

**Issue by gacarrillor** [GeoWerkstatt/qgis-xtf-log-checker#11]
These lines are not getting the expected attribute.

https://github.com/GeoWerkstatt/qgis-xtf-log-checker/blob/0aab28c21703fb61de84fb56e8c3397090ca64dd/xtflog_checker/XTFLog_Checker_dialog.py#L49

https://github.com/GeoWerkstatt/qgis-xtf-log-checker/blob/0aab28c21703fb61de84fb56e8c3397090ca64dd/xtflog_checker/XTFLog_Checker_dialog.py#L115

I think you mean `TechDetails` (https://github.com/claeis/ilivalidator/blob/master/docs/IliVErrors.ili#L29).

**Comment by MiraGeowerkstatt** [comment]
Right! Seems we missed that. Thanks for your contribution. I will release a new version.
