### ISSUE TITLE
Show the dockwidget on top of others

### ISSUE THREAD

**Issue by gacarrillor** [GeoWerkstatt/qgis-xtf-log-checker#8]
Nice idea to visualize and keep track of errors from iliValidator!

Just a UI suggestion here. Instead of

https://github.com/GeoWerkstatt/qgis-xtf-log-checker/blob/8686a48a6a5bc264bc6a66bb61749bf8f455e95d/xtflog_checker/XTFLog_Checker_dialog.py#L196

you could use 

`self.iface.addTabifiedDockWidget(Qt.RightDockWidgetArea, self.dock, raiseTab=True)`

to get the tab at the top of existing dock widgets (tabified).

See https://twitter.com/GeoTux2/status/1268223197578739715 for details.

**Comment by MiraGeowerkstatt** [comment]
Thank you for the great idea! I'll look into it.
